import requests, json, time, re, difflib, pyodbc
from datetime import datetime

BASE = "http://localhost:8080/api"
DB_CONN = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=ushou102-exap1.vinmar.com;"
    "DATABASE=ai;"
    "UID=sean;"
    "PWD=4peiling;"
)

# ── Expected SQL from test plan doc ──────────────────────────────────────────
EXPECTED_SQL = {
    1: ("SELECT COUNT(*) AS InTransitCount FROM Sealine_Tracking "
        "WHERE [Tracking Status] <> 'Delivered'"),

    2: ("SELECT COUNT(*) AS HoustonInTransitCount FROM Sealine_Tracking "
        "WHERE [Tracking Status] <> 'Delivered' "
        "AND ([POL City] LIKE '%Houston%' OR [POL Country] LIKE '%Houston%' OR [POL LOCode] LIKE '%USHOU%')"),

    3: None,  # CTE generated by _tracking_route_sql — validated by map output

    4: None,  # subquery generated by _container_route_sql — validated by map output

    5: ("SELECT DISTINCT TrackNumber FROM Sealine_Tracking "
        "WHERE [POL City] LIKE '%Houston%' "
        "AND ([POD Country] = 'China' OR [POD Country Code] = 'CN') "
        "AND [POD Date] BETWEEN CONVERT(DATE, GETDATE()) AND DATEADD(DAY, 7, CONVERT(DATE, GETDATE()))"),

    6: ("SELECT [POD Country] AS Country, COUNT(*) AS ActiveTrackingCount "
        "FROM Sealine_Tracking "
        "WHERE [Tracking Status] IN ('Pending Departure', 'Departed from Origin', 'Arrived Destination') "
        "GROUP BY [POD Country]"),

    7: None,  # no SQL — geocode/map lookup only

    8: None,  # split-route CTE — validated by result count and structure

    9: ("SELECT TrackNumber, [POD City] AS POD_Location, [POD Latitude] AS Lat, [POD Longitude] AS Lng "
        "FROM Sealine_Tracking "
        "WHERE [Tracking Status] <> 'Delivered' "
        "AND [POD Latitude] IS NOT NULL AND [POD Longitude] IS NOT NULL "
        "AND ( "
        "([POD Latitude] BETWEEN 29 AND 33.5 AND [POD Longitude] BETWEEN 33.8 AND 36.5) OR "
        "([POD Latitude] BETWEEN 41 AND 48 AND [POD Longitude] BETWEEN 28 AND 42) OR "
        "([POD Latitude] BETWEEN 12 AND 28 AND [POD Longitude] BETWEEN 32 AND 52) OR "
        "([POD Latitude] BETWEEN 8 AND 23 AND [POD Longitude] BETWEEN 22 AND 38) ) "
        "ORDER BY TrackNumber"),

    10: ("SELECT t.[POD Country] AS Country, COUNT(DISTINCT e.[Container Name]) AS InTransitContainers "
        "FROM Sealine_Container_Event e "
        "INNER JOIN Sealine_Tracking t ON e.TrackNumber = t.TrackNumber "
        "WHERE t.[Tracking Status] <> 'Delivered' "
        "GROUP BY t.[POD Country]"),
}

def normalize_sql(sql):
    return re.sub(r'\s+', ' ', sql.upper().strip().rstrip(';')).strip()

def compare_sql(actual, expected):
    if expected is None:
        return "SKIPPED (no expected SQL)", 100, []
    a = normalize_sql(actual)
    e = normalize_sql(expected)
    if a == e:
        return "MATCH", 100, []
    ratio = difflib.SequenceMatcher(None, a, e).ratio()
    pct = round(ratio * 100)
    a_words, e_words = a.split(), e.split()
    diff = list(difflib.ndiff(e_words, a_words))
    removed = [w[2:] for w in diff if w.startswith('- ')]
    added   = [w[2:] for w in diff if w.startswith('+ ')]
    diff_lines = []
    if removed: diff_lines.append("    - (in expected, not actual) : " + ' '.join(removed))
    if added:   diff_lines.append("    + (in actual, not expected)  : " + ' '.join(added))
    label = "CLOSE MATCH" if pct >= 85 else "MISMATCH"
    return "%s (%d%%)" % (label, pct), pct, diff_lines

def run_expected_sql(sql):
    """Run expected SQL directly against database to get the ground truth result."""
    try:
        conn = pyodbc.connect(DB_CONN, timeout=10)
        cursor = conn.cursor()
        cursor.execute(sql)
        rows = cursor.fetchall()
        conn.close()
        return rows
    except Exception as e:
        return str(e)

def run_test(question):
    session_id = requests.post("%s/sessions" % BASE, json={"title": "E2E Test"}, timeout=10).json()["session_id"]
    sqls, results, files, raw_parts = [], [], [], []
    with requests.post("%s/sessions/%s/messages" % (BASE, session_id),
                       json={"message": question}, stream=True, timeout=300) as resp:
        for line in resp.iter_lines():
            if not line: continue
            raw = line.decode("utf-8", errors="replace")
            if not raw.startswith("data:"): continue
            try:
                data = json.loads(raw[5:].strip())
                if "query" in data and "tool" in data:    sqls.append(data["query"])
                elif "result" in data and "tool" in data: results.append(data["result"])
                elif "file" in data:                      files.append(data["file"])
                raw_parts.append(json.dumps(data))
            except: pass
    return sqls, results, files, "\n".join(raw_parts)

def extract_count(result_text):
    """Extract first number from result text."""
    nums = re.findall(r'\d+', result_text.replace(",", ""))
    return int(nums[0]) if nums else None

def p(s=""): print(s)

p("=== E2E TEST REPORT - Sealine Data Chat ===")
p("Run time: %s" % datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
p()

passed = 0; sql_matched = 0; total_warnings = 0; N = 10

# ── TEST 1 ──────────────────────────────────────────────────────────────────
p("Running test 1...")
sqls, db_results, files, raw = run_test("How many tracking are in transit.")
time.sleep(2)
sql   = sqls[0] if sqls else "NO SQL CAPTURED"
dout  = db_results[0].strip() if db_results else "NO RESULT"
count = extract_count(dout)
# Checkpoint: compare against expected SQL result
expected_rows = run_expected_sql(EXPECTED_SQL[1])
expected_count = expected_rows[0][0] if expected_rows and not isinstance(expected_rows, str) else None
tolerance = 0.10  # 10% tolerance
if expected_count and count:
    lo = int(expected_count * (1 - tolerance))
    hi = int(expected_count * (1 + tolerance))
else:
    lo, hi = 1500, 2500
st    = "PASS" if count is not None and lo <= count <= hi else "FAIL"
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[1])
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 1 - How many tracking are in transit.")
p("  Status        : %s" % st)
p("  Expected count: %s (tolerance: %d - %d)" % (expected_count, lo, hi))
p("  Actual count  : %s" % (count if count is not None else "UNKNOWN"))
p("  Generated SQL : %s" % sql)
p("  Expected SQL  : %s" % EXPECTED_SQL[1])
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 2 ──────────────────────────────────────────────────────────────────
p("\nRunning test 2...")
sqls, db_results, files, raw = run_test("How many in transit tracking depart from Houston.")
time.sleep(2)
sql   = sqls[0] if sqls else "NO SQL CAPTURED"
dout  = db_results[0].strip() if db_results else "NO RESULT"
count = extract_count(dout)
expected_rows = run_expected_sql(EXPECTED_SQL[2])
expected_count = expected_rows[0][0] if expected_rows and not isinstance(expected_rows, str) else None
if expected_count and count:
    lo = int(expected_count * (1 - tolerance))
    hi = int(expected_count * (1 + tolerance))
else:
    lo, hi = 800, 1500
st    = "PASS" if count is not None and lo <= count <= hi else "FAIL"
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[2])
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 2 - How many in transit tracking depart from Houston.")
p("  Status        : %s" % st)
p("  Expected count: %s (tolerance: %d - %d)" % (expected_count, lo, hi))
p("  Actual count  : %s" % (count if count is not None else "UNKNOWN"))
p("  Generated SQL : %s" % sql)
p("  Expected SQL  : %s" % EXPECTED_SQL[2])
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 3 ──────────────────────────────────────────────────────────────────
p("\nRunning test 3...")
sqls, db_results, files, raw = run_test("show me the route for trackings 038NY1490725, 038NY1485768")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
html_found   = bool(files) or bool(re.search(r'[\w\-]+\.html', raw))
map_file     = files[0] if files else "(in stream)"
view_ok      = "SEALINE_TRACKING" in su
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[3])
st = "PASS" if (view_ok and html_found) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 3 - show me the route for trackings 038NY1490725, 038NY1485768")
p("  Status        : %s" % st)
p("  Map generated : %s" % ("YES - " + str(map_file) if html_found else "NO"))
p("  View used     : %s" % ("Sealine_Tracking [OK]" if view_ok else "WRONG VIEW [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 4 ──────────────────────────────────────────────────────────────────
p("\nRunning test 4...")
sqls, db_results, files, raw = run_test("show me the containers route map for tracking 038VH9479901 and 038VH9465510")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
html_found   = bool(files) or bool(re.search(r'[\w\-]+\.html', raw))
map_file     = files[0] if files else "(in stream)"
view_ok      = "SEALINE_CONTAINER_EVENT" in su
vessel_ok    = "VESSEL" in su
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[4])
st = "PASS" if (view_ok and html_found and vessel_ok) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 4 - show me the containers route map for tracking 038VH9479901 and 038VH9465510")
p("  Status        : %s" % st)
p("  Map generated : %s" % ("YES - " + str(map_file) if html_found else "NO"))
p("  View used     : %s" % ("Sealine_Container_Event [OK]" if view_ok else "WRONG VIEW [FAIL]"))
p("  Vessel col    : %s" % ("present [OK]" if vessel_ok else "MISSING [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 5 ──────────────────────────────────────────────────────────────────
p("\nRunning test 5...")
sqls, db_results, files, raw = run_test("list all the tracking numbers from houston to china and will arrive in next 7 days")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
houston_ok   = "HOUSTON" in su or "USHOU" in su
china_ok     = "CHINA" in su or "CN" in su
date_ok      = "GETDATE" in su and "7" in su
pol_ok       = "POL" in su
pod_ok       = "POD" in su
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[5])
st = "PASS" if (houston_ok and china_ok and date_ok and pol_ok and pod_ok) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 5 - list all tracking numbers from Houston to China arriving in next 7 days")
p("  Status        : %s" % st)
p("  Houston filter: %s" % ("OK" if houston_ok else "MISSING [FAIL]"))
p("  China filter  : %s" % ("OK" if china_ok   else "MISSING [FAIL]"))
p("  7-day window  : %s" % ("OK" if date_ok    else "MISSING [FAIL]"))
p("  POL/POD types : %s" % ("OK" if (pol_ok and pod_ok) else "MISSING [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  Expected SQL  : %s" % EXPECTED_SQL[5])
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 6 ──────────────────────────────────────────────────────────────────
p("\nRunning test 6...")
sqls, db_results, files, raw = run_test("show me all active tracking count by POD country in a shaded country map")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
html_found   = bool(files) or bool(re.search(r'[\w\-]+\.html', raw))
country_ok   = "COUNTRY" in su
pod_ok       = "POD" in su
group_ok     = "GROUP BY" in su
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[6])
st = "PASS" if (country_ok and pod_ok and group_ok and html_found) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 6 - show me all active tracking count by POD country in a shaded country map")
p("  Status        : %s" % st)
p("  Map generated : %s" % ("YES" if html_found else "NO [FAIL]"))
p("  Country col   : %s" % ("OK" if country_ok else "MISSING [FAIL]"))
p("  POD filter    : %s" % ("OK" if pod_ok     else "MISSING [FAIL]"))
p("  GROUP BY      : %s" % ("OK" if group_ok   else "MISSING [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  Expected SQL  : %s" % EXPECTED_SQL[6])
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 7 ──────────────────────────────────────────────────────────────────
p("\nRunning test 7...")
sqls, db_results, files, raw = run_test("show me Jawaharlal Nehru, IN (INNSA) in the map")
time.sleep(2)
html_found = bool(files) or bool(re.search(r'[\w\-]+\.html', raw))
innsa_ok   = "INNSA" in raw.upper() or "JAWAHARLAL" in raw.upper() or "NHAVA" in raw.upper()
st = "PASS" if (html_found and innsa_ok) else "FAIL"
if st == "PASS": passed += 1
sql_matched += 1  # no SQL expected, count as matched
p("\nTEST 7 - show me Jawaharlal Nehru, IN (INNSA) in the map")
p("  Status        : %s" % st)
p("  Map generated : %s" % ("YES" if html_found else "NO [FAIL]"))
p("  Port found    : %s" % ("YES" if innsa_ok   else "NO [FAIL]"))
p("  (No SQL expected for this test)")

# ── TEST 8 ──────────────────────────────────────────────────────────────────
p("\nRunning test 8...")
sqls, db_results, files, raw = run_test("show me the tracking with split-route")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
dout     = db_results[0].strip() if db_results else "NO RESULT"
# Count result rows
data_lines = [l for l in dout.split('\n') if l.strip() and not any(x in l.lower() for x in ['tracknumber', 'no of containers', 'no of locations', 'split routes', '---', '='])]
count = len(data_lines) if data_lines else None
view_ok      = "SEALINE_CONTAINER_EVENT" in su
having_ok    = "HAVING" in su
rownumber_ok = "ROW_NUMBER" in su
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[8])
st = "PASS" if (view_ok and having_ok and rownumber_ok and count is not None and count < 50) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 8 - show me the tracking with split-route")
p("  Status        : %s" % st)
p("  Result count  : %s (expected < 50)" % (count if count is not None else "UNKNOWN"))
p("  View used     : %s" % ("Sealine_Container_Event [OK]" if view_ok else "WRONG [FAIL]"))
p("  HAVING clause : %s" % ("OK" if having_ok    else "MISSING [FAIL]"))
p("  ROW_NUMBER    : %s" % ("OK" if rownumber_ok else "MISSING [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 9 ──────────────────────────────────────────────────────────────────
p("\nRunning test 9...")
sqls, db_results, files, raw = run_test("list all the tracking are in transit, not delivered and the POD location is in the war zones.")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
dout     = db_results[0].strip() if db_results else "NO RESULT"
data_lines = [l for l in dout.split('\n') if l.strip() and not any(x in l.lower() for x in ['tracknumber', 'pod_location', 'pod location', '---', '='])]
count = len(data_lines) if data_lines else None
warzone_ok   = any(x in su for x in ["BETWEEN 29", "BETWEEN 41", "BETWEEN 12", "BETWEEN 8"])
pod_ok       = "POD" in su
transit_ok   = "DELIVERED" in su or "TRACKING STATUS" in su
# Checkpoint: compare result against expected SQL
expected_rows = run_expected_sql(EXPECTED_SQL[9])
expected_count = len(expected_rows) if expected_rows and not isinstance(expected_rows, str) else None
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[9])
st = "PASS" if (warzone_ok and pod_ok and transit_ok) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 9 - tracking with POD in war zones, in transit and not delivered")
p("  Status        : %s" % st)
p("  Result count  : %s (expected: %s)" % (count if count is not None else "UNKNOWN", expected_count))
p("  War zone bbox : %s" % ("OK" if warzone_ok  else "MISSING [FAIL]"))
p("  POD filter    : %s" % ("OK" if pod_ok      else "MISSING [FAIL]"))
p("  Transit filter: %s" % ("OK" if transit_ok  else "MISSING [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  Expected SQL  : %s" % EXPECTED_SQL[9])
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── TEST 10 ─────────────────────────────────────────────────────────────────
p("\nRunning test 10...")
sqls, db_results, files, raw = run_test("show me number of containers in transit group the result by POD country. Show the result in a shaded map")
time.sleep(2)
sql      = sqls[0] if sqls else "NO SQL CAPTURED"
su       = sql.upper()
html_found   = bool(files) or bool(re.search(r'[\w\-]+\.html', raw))
country_ok   = "COUNTRY" in su
pod_ok       = "POD" in su
join_ok      = "INNER JOIN" in su or "JOIN" in su
group_ok     = "GROUP BY" in su
container_ok = "CONTAINER" in su
sq_label, sq_pct, sq_diff = compare_sql(sql, EXPECTED_SQL[10])
st = "PASS" if (country_ok and pod_ok and join_ok and group_ok and container_ok and html_found) else "FAIL"
if st == "PASS":  passed += 1
if sq_pct >= 85:  sql_matched += 1
p("\nTEST 10 - containers in transit group the result by POD country, shaded map")
p("  Status        : %s" % st)
p("  Map generated : %s" % ("YES" if html_found else "NO [FAIL]"))
p("  Country col   : %s" % ("OK" if country_ok  else "MISSING [FAIL]"))
p("  POD filter    : %s" % ("OK" if pod_ok      else "MISSING [FAIL]"))
p("  INNER JOIN    : %s" % ("OK" if join_ok     else "MISSING [FAIL]"))
p("  GROUP BY      : %s" % ("OK" if group_ok    else "MISSING [FAIL]"))
p("  Container ref : %s" % ("OK" if container_ok else "MISSING [FAIL]"))
p("  Generated SQL : %s" % sql)
p("  Expected SQL  : %s" % EXPECTED_SQL[10])
p("  SQL match     : %s" % sq_label)
for d in sq_diff: p(d)

# ── SUMMARY ─────────────────────────────────────────────────────────────────
p()
p("=" * 50)
p("SUMMARY")
p("  Tests passed  : %d / %d" % (passed, N))
p("  SQL match     : %d / %d (exact or close match >= 85%%)" % (sql_matched, N))
p("  Overall       : %s" % ("ALL PASS" if passed == N else "%d FAILED" % (N - passed)))
p("=" * 50)
